### ISSUE TITLE
node error on 'nad_circapi" with latest version of nad

### ISSUE THREAD

**Issue by sax** [circonus-labs/nad#19]
When installing the latest version of nad, I get the following error when starting it up or running any command-line options:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'nad_circapi'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/circonus/sbin/nad:17:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

This is on SmartOS base64 images.

**Comment by postwait** [comment]
I believe this has long been addressed.
